"""User-defined asset baskets: create, update, aggregate across basket."""
class BasketManager:
    def create_basket(self, name: str, tickers: list): ...
    def get_basket_score(self, name: str, window: str) -> dict: ...
