# Local dev stack: Postgres, Redis, Kafka, Elasticsearch
version: "3.9"
services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: esm
      POSTGRES_PASSWORD: devpass
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports: ["9092:9092"]
  elasticsearch:
    image: elasticsearch:8.13.0
    ports: ["9200:9200"]
    environment:
      discovery.type: single-node
  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
  prometheus:
    image: prom/prometheus:latest
    ports: ["9090:9090"]